# Generated by Django 5.2.15 on 2026-07-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Hardware, Software)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category')),
                ('icon', models.CharField(blank=True, help_text='Image', max_length=50)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code for UI (e.g., #dc3545 for red)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is this category active and available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket Category',
                'verbose_name_plural': 'Ticket Categories',
                'ordering': ['name'],
            },
        ),
    ]
