# Generated by Django 5.2.15 on 2026-07-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type name (e.g., Bug, Feature Request)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this type')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon name (e.g., fa-bug, fa-star)', max_length=50)),
                ('color', models.CharField(default='#17a2b8', help_text='Hex color code for UI (e.g., #dc3545 for red)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is this type active and available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket Type',
                'verbose_name_plural': 'Ticket Types',
                'ordering': ['name'],
            },
        ),
    ]
