# Generated by Django 5.2.15 on 2026-07-11 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_ticketcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of this SLA rule (e.g., 'Emergency SLA')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this SLA rule')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Which priority level does this SLA apply to?', max_length=20, unique=True)),
                ('response_time_minutes', models.IntegerField(help_text='Maximum minutes to first respond')),
                ('resolution_time_minutes', models.IntegerField(help_text='Maximum minutes to resolve')),
                ('is_active', models.BooleanField(default=True, help_text='Is this SLA rule active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SLA Rule',
                'verbose_name_plural': 'SLA Rules',
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, help_text='When was the first response made?', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_resolution_breached',
            field=models.BooleanField(default=False, help_text='Has the resolution SLA been breached?'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_resolution_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for resolution', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_response_breached',
            field=models.BooleanField(default=False, help_text='Has the response SLA been breached?'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_response_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for first response', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_status',
            field=models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('breached', 'Breached')], default='on_track', help_text='Current SLA status', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', editable=False, help_text='Automatically calculated priority', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla',
            field=models.ForeignKey(blank=True, help_text='SLA rule applied to this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.sla'),
        ),
    ]
