# Generated by Django 5.2.15 on 2026-07-18 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_sla_ticket_first_response_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, help_text='Keyword to search for in description', max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Priority to assign', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Lower number = checked first')),
                ('is_active', models.BooleanField(default=True, help_text='Is this rule active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category to match (leave blank for any)', null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketcategory')),
                ('type', models.ForeignKey(blank=True, help_text='Type to match (leave blank for any)', null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype')),
            ],
            options={
                'verbose_name': 'Priority Rule',
                'verbose_name_plural': 'Priority Rules',
                'ordering': ['order'],
            },
        ),
    ]
