# Generated by Django 5.2.12 on 2026-07-19 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_priorityrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('on_break', 'On Break'), ('in_meeting', 'In Meeting'), ('offline', 'Offline'), ('sick', 'Sick')], default='available', help_text='Current availability status', max_length=20)),
                ('max_ticket_load', models.IntegerField(default=10, help_text='Maximum number of open tickets this agent can handle')),
                ('is_active', models.BooleanField(default=True, help_text='Is this agent actively taking tickets?')),
                ('last_assigned_at', models.DateTimeField(blank=True, help_text='When this agent was last assigned a ticket', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(help_text='The agent', on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Availability',
                'verbose_name_plural': 'Agent Availability',
            },
        ),
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strategy', models.CharField(choices=[('least_busy', 'Least Busy'), ('round_robin', 'Round Robin'), ('skill_based', 'Skill Based')], default='least_busy', max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Apply this rule only to this priority (leave blank for all)', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Apply this rule only to this category (leave blank for all)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketcategory')),
            ],
            options={
                'verbose_name': 'Assignment Rule',
                'verbose_name_plural': 'Assignment Rules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AgentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5, help_text='Proficiency level (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='The agent with this skill', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='The category this agent is skilled in', on_delete=django.db.models.deletion.CASCADE, related_name='skilled_agents', to='tickets.ticketcategory')),
            ],
            options={
                'verbose_name': 'Agent Skill',
                'verbose_name_plural': 'Agent Skills',
                'ordering': ['agent__username', 'category__name'],
                'unique_together': {('agent', 'category')},
            },
        ),
    ]
