# Generated by Django 5.2.15 on 2026-07-24 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_report_reportschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name (e.g., HR, Finance, IT)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this department')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon name (e.g., fa-users, fa-building)', max_length=50)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code for UI', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is this department active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Which department this ticket is from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.department'),
        ),
    ]
