# Generated by Django 5.2.15 on 2026-07-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_department_ticket_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ticket Creation', 'verbose_name_plural': 'Ticket Creation'},
        ),
        migrations.AlterField(
            model_name='department',
            name='color',
            field=models.CharField(blank=True, default='#6c757d', help_text='Hex color code for UI', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon name (e.g., fa-users, fa-building)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='color',
            field=models.CharField(blank=True, default='#6c757d', help_text='Hex color code for UI', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Image', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='color',
            field=models.CharField(default='#17a2b8', help_text='Hex color code for UI (e.g., #dc3545 for red)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon name (e.g., fa-bug, fa-star)', max_length=50, null=True),
        ),
    ]
