# Generated by Django 5.2.15 on 2026-08-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_options_alter_department_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, help_text='Unique ticket number (e.g., T-H-001)', max_length=20, null=True, unique=True),
        ),
    ]
